### ISSUE TITLE
Always show content

### ISSUE THREAD

**Issue by marekche** [mounthorse-slns/angular-calendar-scheduler#44]
How i can always show the content text?
If the event is less than 3 hours, the content text are not showing.

Thank you!

**Comment by mounthorse-slns** [comment]
Hi @marekche , could you create a stackblitz or something else to reproduce that? I'll give it a look.

**Comment by marekche** [comment]
Hi @mounthorse-slns
For example, in the original demo (https://angular-calendar-scheduler-demo.stackblitz.io), the event N°53 are not showing the content. I think that if you change this event more than 30min it will show the content!

**Comment by mounthorse-slns** [comment]
Hi @marekche , I've fixed that and published the version 10.0.7. Check it out and let me know if it's ok now ;)

**Comment by marekche** [comment]
Thank you!
