### ISSUE TITLE
Time Intervals

### ISSUE THREAD

**Issue by marekche** [mounthorse-slns/angular-calendar-scheduler#45]
I'm using Angular 11 on my project!
When I add segmentHours the scheduler divide the hours but not show the interval times on the scheduler.
When I clicked over a segment it shows the correct time.

Example: https://angular-q9xcmb.stackblitz.io/

Thanks in advance!

**Comment by mounthorse-slns** [comment]
@marekche share the code on stackblitz pls.

**Comment by marekche** [comment]
@mounthorse-slns Here is: https://angular-q9xcmb.stackblitz.io/

**Comment by mounthorse-slns** [comment]
@marekche  I see this at that link, not the code.

![Immagine 2021-01-15 193159](https://user-images.githubusercontent.com/19502861/104764943-60f7cd00-5768-11eb-9389-63988804299a.png)

**Comment by marekche** [comment]
https://stackblitz.com/edit/angular-q9xcmb

I have the provider configured also.

**Comment by marekche** [comment]
You right! My mistake!

Thank you again!
