### ISSUE TITLE
Event View on Firefox

### ISSUE THREAD

**Issue by berdanA** [mounthorse-slns/angular-calendar-scheduler#56]
Hi, i wanted to know, if this project was meant to be supported by Firefox, since it provides a view for mattlewis92/angular-calendar, which, as far as I understand, supports Firefox.

I had no issues so far with Chrome, Edge or Safari. Just on Firefox I have this problem, where the events are not shown fully or rather do not fill their container fully, thus making their time span appear much smaller than it should be. I looked at the demo and its the same there.

I have provided a Screenshot of this problem. Firefox on the right and Chrome on the left. Event 7 appears much shorter in Firefox then Chrome.

![image](https://user-images.githubusercontent.com/80056664/122457236-ba318a00-cfae-11eb-9f4b-0ec7ee8a1f2e.png)

**Comment by mounthorse-slns** [comment]
Hi @berdanA , after the update to angular 14 and bootstrap 5 I'm not able to reproduce the problem.
I suppose that it fixed itself ;)
