### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by Sam-Davis** [mounthorse-slns/angular-calendar-scheduler#58]
This is just slightly out of date: https://www.npmjs.com/package/angular-calendar-scheduler#getting-started

DateAdapter can be found included in this version: 
https://github.com/mounthorse-slns/angular-calendar-scheduler/blob/master/src/app/app.component.ts

**Comment by Sam-Davis** [comment]
also CalendarView instead of CalendarPeriod as arg in ChangeView

**Comment by mounthorse-slns** [comment]
Thank you, I've updated the readme with your suggestions.


Michele Bombardi
*Senior Consultant & Software Engineer*
mobile: +39 3467212314
email: ***@***.*** ***@***.***>
<https://www.linkedin.com/in/michele-bombardi-47318258/>


Il giorno mer 4 ago 2021 alle ore 10:46 Sam-Davis ***@***.***>
ha scritto:
