### ISSUE TITLE
Does this angular-calendar-scheduler works with Angular 5

### ISSUE THREAD

**Issue by Nitinchavda** [mounthorse-slns/angular-calendar-scheduler#8]
Hello There,

I'm trying to use angular-calendar-scheduler in angular 5 version but it didn't works and getting  multiple errors.

If it's working with Angular 5 than can you tell me which version of angular-calendar-scheduler suitable?.

Many Thanks.
Nitin

**Comment by mounthorse-slns** [comment]
Hi,
the library is updated to Angular 7.X.X version.
You need to use that version to make angular-calendar-scheduler to work :)

**Comment by Nitinchavda** [comment]
Ok, Thanks for the quick reply. So there is no way to use this lib for older version of angular like 5.x right?

**Comment by mounthorse-slns** [comment]
Unfortunately no, sorry :(
