### ISSUE TITLE
Bump Bootstrap dependency from 4.4.1 to 5.x

### ISSUE THREAD

**Issue by bjornharvold** [mounthorse-slns/angular-calendar-scheduler#84]
Would be nice to know that it's compatible with latest version of Bootstrap.

🦸‍♂️

**Comment by mounthorse-slns** [comment]
Hi,
It is not compatible with bootstrap 5.x actually.
I'll update it soon.

Thank you very much!

**Comment by mounthorse-slns** [comment]
@bjornharvold The version 14.0.1 is released and it is fully compatible with angular 14+ and boostrap 5.
