### ISSUE TITLE
Null injector for MOMENT

### ISSUE THREAD

**Issue by avelenivius** [mounthorse-slns/angular-calendar-scheduler#87]
Hi, first of all thanks for providing such a nice package and maintaining it!
I would like to request some assistance with a problem I'm experiencing (although I'm not sure if that's the correct place for it): 
```
NullInjectorError: R3InjectorError(AppModule)[CalendarSchedulerUtils -> InjectionToken Moment -> InjectionToken Moment -> InjectionToken Moment]: 
  NullInjectorError: No provider for InjectionToken Moment!
```
I can't seem to work out what is the problem, I followed both README guides to set up both libraries in my project. My NgModule import:
```
    CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory // 'angular-calendar/date-adapters/date-fns'
    }),
    SchedulerModule.forRoot({
      locale: 'pl',
      headerDateFormat: 'daysRange'
    })
```
My component providers:
```
providers: [
    {
      provide: CalendarDateFormatter,
      useClass: SchedulerDateFormatter
    }
  ]
```
And dependency versions from package.json:
```
    "angular-calendar": "^0.30.1",
    "angular-calendar-scheduler": "^14.2.0",
    "date-fns": "^2.29.2",
```

**Comment by mounthorse-slns** [comment]
Hi @avelenivius,
Sorry, I forgot to update the readme.
Due to the update to Angular 14, the `Moment` library must be provided from the main application.

I've just updated the instructions, see the readme in the _Import_ section for details.

I close this but feel free to reopen the issue if the issue persists ;)

**Comment by uKioops** [comment]
Had the same problem, checked with the actual source code, on angular 15, you'll need to import MOMENT from the angular-calendar to avoid the nullinjector error. Also other imports are needed.

```
import { CalendarModule, DateAdapter, MOMENT } from 'angular-calendar';
import { SchedulerModule } from 'angular-calendar-scheduler';
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';
import * as moment from 'moment';


@NgModule({
    ...
    imports: [
        ...,
        CalendarModule.forRoot({
          provide: DateAdapter,
          useFactory: adapterFactory,}),
        SchedulerModule.forRoot({ locale: 'en', headerDateFormat: 'daysRange' }),
        ...
    ],
    providers: [
        ...
        { provide: LOCALE_ID, useValue: 'en-US' },
        { provide: MOMENT, useValue: moment }
        ...
    ],
    ...
})
class AppModule { }
```
