### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by co-dax** [mounthorse-slns/angular-calendar-scheduler#88]
Hey, may I ask a dumb question? What it is the purpose of this project? As far as I can see it illustrates how [https://github.com/mattlewis92/angular-calendar](https://github.com/mattlewis92/angular-calendar) works and that kind of page is already available [here](https://mattlewis92.github.io/angular-calendar/#/kitchen-sink)

I must be missing something....

Thanks!

**Comment by mounthorse-slns** [comment]
Hi @co-dax I've developed this library many years ago when mattlewis92 hadn't implemented a similar functionality yet.
Then I've kept that because in my projects I still use this and not the mattlewis92's library directly.

**Comment by co-dax** [comment]
Thaks @mounthorse-slns !
